version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "8080:8080"
    deploy:
      replicas: 3 
    depends_on:
      - backend

  backend:
    build: ./backend
    container_name: todo-backend
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=examplepassword
      - DB_NAME=tododb
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    container_name: todo-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: examplepassword
      POSTGRES_DB: tododb
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db-data:
