version: '3.8'

services:
  frontend:
    image: ravikc/todo-frontend:latest
    ports:
      - "8080:8080"
    deploy:
      replicas: 3
      placement:
        constraints: [node.role == worker]
      restart_policy:
        condition: on-failure
    networks:
      - todo-net

  backend:
    image: ravikc/todo-backend:latest
    ports:
      - "3000:3000"
    deploy:
      replicas: 2
      placement:
        constraints: [node.role == worker]
      restart_policy:
        condition: on-failure
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=examplepassword
      - DB_NAME=tododb
    networks:
      - todo-net

  db:
    image: postgres:16-alpine
    container_name: todo-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: examplepassword
      POSTGRES_DB: tododb
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == manager]
    networks:
      - todo-net

volumes:
  db-data:

networks:
  todo-net:
    driver: overlay
